#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
cd $OPENSHIFT_REPO_DIR/payload
SBT_PATH=$OPENSHIFT_DATA_DIR/sbt
SBT_DIR=$OPENSHIFT_DATA_DIR/.sbt
IVY_DIR=$OPENSHIFT_DATA_DIR/.ivy
PATH=$OPENSHIFT_DATA_DIR/sbt/bin:$PATH
nohup sbt -sbt-dir $SBT_DIR -ivy $IVY_DIR run > $OPENSHIFT_DIY_DIR/logs/server.log 2>&1 &
